version: '3'
services:
  postgres:
    image: postgres:12.16
    volumes:
      - postgresql_data:/var/lib/postgresql-receitas/data
    hostname: postgres
    environment:
      - POSTGRES_DB=receitas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
    ports:
      - "${DB_PORT}:5432"
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    ports:
      - "8001:8001"

volumes:
  postgresql_data:
