apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - args:
            - bash
            - -c
            - |-
              python wait_for_postgres.py &&
                       ./manage.py migrate &&
                       gunicorn --bind 0.0.0.0:8000 --access-logfile - receitas.wsgi:application
          env:
            - name: DJANGO_SECRET_KEY
              value: local
          image: tutorial_python_brasil_2023
          imagePullPolicy: Never
          name: web
          ports:
            - name: gunicorn
              containerPort: 8000
          resources: {}
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: gunicorn
              path: /
          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - /bin/sh
                - -c 
                - "pidof -x gunicorn"
      restartPolicy: Always
status: {}
